export const data = [
    {
      id: 1,
      iconos: ["🍚", "🫘", "🍞"],
      categoria: "Cereales, Granos y Carbohidratos",
      subcategorias: "Arroz, Harina, Pasta, Avena, Legumbres, Pan, Café, Cereales Azucarados",
      marcas: [
        { logo: "/logos/amanecer.png", nombre: "Amanecer" },
        { logo: "/logos/primor.png", nombre: "Primor" },
        { logo: "/logos/mary.png", nombre: "Mary" },
        { logo: "/logos/pan.png", nombre: "PAN" },
      ],
      skus: "",
    },
    {
      id: 2,
      iconos: ["🍎", "🥦", "🥕"],
      categoria: "Frutas, verduras y Tubérculos",
      subcategorias: "Frutas, Vegetales, Verduras, Tubérculos",
      marcas: [
        { logo: "/logos/manzana.png", nombre: "Frutas" },
        { logo: "/logos/zanahoria.png", nombre: "Vegetales" },
        { logo: "/logos/brocoli.png", nombre: "Vegetales" },
      ],
      skus: "",
    },
    {
      id: 3,
      iconos: ["🍗", "🥩", "🐟"],
      categoria: "Proteínas",
      subcategorias: "Pollo, Cerdo, Res, Pescado y mariscos, Cordero, Huevos",
      marcas: [
        { logo: "/logos/eltunal.png", nombre: "Alimentos El Tunal" },
        { logo: "/logos/delcorral.png", nombre: "del Corral" },
        { logo: "/logos/purolomo.png", nombre: "Purolomo" },
      ],
      skus: "",
    },
    {
      id: 4,
      iconos: ["🥛", "🍦", "🧃"],
      categoria: "Lácteos y derivados",
      subcategorias: "Leche, Bebidas lácteas, Yogurt, Mantequillas",
      marcas: [
        { logo: "/logos/fritz.png", nombre: "Fritz" },
        { logo: "/logos/nestle.png", nombre: "Nestle" },
        { logo: "/logos/purisima.png", nombre: "purisima" },
        { logo: "/logos/paisa.png", nombre: "paisa" },
      ],
      skus: 1,
    },
    {
      id: 5,
      iconos: ["🍖", "🌭", "🥓"],
      categoria: "Embutidos",
      subcategorias: "Jamón, Salchicha, Mortadela, Morcilla, Chorizo, Salami",
      marcas: [
        { logo: "/logos/plumrose.png", nombre: "Plumrose" },
        { logo: "/logos/lprado.png", nombre: "lprado" },
        { logo: "/logos/purolomo.png", nombre: "Purolomo" },
      ],
      skus: "",
    },
    {
      id: 6,
      iconos: ["🫒", "🧈", "🥜"],
      categoria: "Grasas y aceites",
      subcategorias: "Aceite, Mantequilla de maní, Margarina, Otras grasas",
      marcas: [
        { logo: "/logos/mavesa.png", nombre: "mavesa" },
        { logo: "/logos/nelly.png", nombre: "nelly" },
        { logo: "/logos/vatel.png", nombre: "vatel" },
      ],
      skus: "",
    },
    {
      id: 7,
      iconos: ["🍯", "🍫", "🍪"],
      categoria: "Dulces y Snack",
      subcategorias: "Azucar y endulzantes, Gelatinas y pudin, Caramelos, Chocolates, Galletas y ponqués, Papas y tostones, Compotas y mermeladas, Helados, Frutos secos",
      marcas: [
        { logo: "/logos/fritz.png", nombre: "Fritz" },
        { logo: "/logos/mondelez.png", nombre: "mondelez" },
        { logo: "/logos/nestle.png", nombre: "nestle" },
        { logo: "/logos/pepsico.png", nombre: "pepsico" },
      ],
      skus: 6,
    },
    {
      id: 8,
      iconos: ["💧", "🥤", "⚡"],
      categoria: "Bebidas",
      subcategorias: "Jugo de frutas, Agua, Gaseosa, Malta, Bebidas achoco, Bebidas energizantes, Té	",
      marcas: [
        { logo: "/logos/cocacola.png", nombre: "cocacola" },
        { logo: "/logos/pepsi.png", nombre: "pepsi" },
        { logo: "/logos/nestle.png", nombre: "nestle" },
        { logo: "/logos/natulac.png", nombre: "natulac" },
      ],
      skus: "",
    },
    {
      id: 9,
      iconos: ["🥫", "🌶️", "🧂"],
      categoria: "Salsas, aderezos y condimentos",
      subcategorias: "Ketchup, Mostaza, Mayonesa, Salsas saborizadas, Vinagre, Sasonadores, Bases en polvo, Condimentos",
      marcas: [
        { logo: "/logos/fritz.png", nombre: "Fritz" },
        { logo: "/logos/iberia.png", nombre: "iberia" },
        { logo: "/logos/kraftheinz.png", nombre: "kraftheinz" },
        { logo: "/logos/mccormick.png", nombre: "mccormick" },
      ],
      skus: 51,
    },
    {
      id: 10,
      iconos: ["🍎", "🥦", "🥕"],
      categoria: "Desechables Food Service",
      subcategorias: "Servilletas, Utensilios, Envases, Papel aluminio, Otros",
      marcas: [
        { logo: "/logos/selva.png", nombre: "Selva" },
      ],
      skus: "",
    },
  ];
  