export const dataClasificacion = [
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Emulsiones",
        producto: "Salsa Sabor a Maíz 240gr",
        imagen: "/placeholder.svg",
        
        categoria: "Salsas, aderezos y condimentos",
        subcategoria: "Salsas saborizadas",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Emulsiones",
        producto: "Salsa Sabor A Queso Cheddar 240gr",
        imagen: "/placeholder.svg",
        
        categoria: "Salsas, aderezos y condimentos",
        subcategoria: "Salsas saborizadas",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Emulsiones",
        producto: "Salsa Sabor A Tocineta 240gr",
        imagen: "/placeholder.svg",
        
        categoria: "Salsas, aderezos y condimentos",
        subcategoria: "Salsas saborizadas",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Emulsiones",
        producto: "Salsa Tártara 240gr",
        imagen: "/placeholder.svg",
        
        categoria: "Salsas, aderezos y condimentos",
        subcategoria: "Salsas saborizadas",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Emulsiones",
        producto: "Mayonesa 240gr",
        imagen: "/placeholder.svg",
        
        categoria: "Salsas, aderezos y condimentos",
        subcategoria: "Salsas saborizadas",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Emulsiones",
        producto: "Salsa Rosada 260gr",
        imagen: "/placeholder.svg",
        
        categoria: "Salsas, aderezos y condimentos",
        subcategoria: "Salsas saborizadas",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Emulsiones",
        producto: "Aderezo de Mostaza y Miel 250gr",
        imagen: "/placeholder.svg",
        
        categoria: "Salsas, aderezos y condimentos",
        subcategoria: "Salsas saborizadas",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Emulsiones",
        producto: "Mostaza Preparada 250gr",
        imagen: "/placeholder.svg",
        
        categoria: "Salsas, aderezos y condimentos",
        subcategoria: "Salsas saborizadas",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Emulsiones",
        producto: "Hot. Salsa Sabor A Maíz 740gr",
        imagen: "/placeholder.svg",
         
        categoria: "Salsas, aderezos y condimentos",
        subcategoria: "Salsas saborizadas",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Emulsiones",
        producto: "Hot. Salsa Sabor a Queso Cheddar 740gr",
        imagen: "/placeholder.svg",
         
        categoria: "Salsas, aderezos y condimentos",
        subcategoria: "Salsas saborizadas",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Emulsiones",
        producto: "Salsa Sabor a Queso Cheddar Galón 3200gr",
        imagen: "/placeholder.svg",
        
        categoria: "Salsas, aderezos y condimentos",
        subcategoria: "Salsas saborizadas",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Emulsiones",
        producto: "Preparado de Mayonesa Bolsa 1kg",
        imagen: "/placeholder.svg",
        
        categoria: "Salsas, aderezos y condimentos",
        subcategoria: "Salsas saborizadas",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Emulsiones",
        producto: "Preparado de Mayonesa Bolsa 3,35kg",
        imagen: "/placeholder.svg",
        
        categoria: "Lácteos y derivados",
        subcategoria: "Salsas saborizadas",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Emulsiones",
        producto: "Aderezo de Mostaza Bolsa 1kg",
        imagen: "/placeholder.svg",
        
        categoria: "Lácteos y derivados",
        subcategoria: "Salsas saborizadas",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Emulsiones",
        producto: "Aderezo de Mostaza Bolsa 3,6kg",
        imagen: "/placeholder.svg",
        
        categoria: "Lácteos y derivados",
        subcategoria: "Salsas saborizadas",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Emulsiones",
        producto: "Mostaza Galón 3800gr",
        imagen: "/placeholder.svg",
        
        categoria: "Lácteos y derivados",
        subcategoria: "Mayonesa",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Emulsiones",
        producto: "Hot. Salsa Tártara 740gr",
        imagen: "/placeholder.svg",
        
        categoria: "Lácteos y derivados",
        subcategoria: "Mayonesa",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Emulsiones",
        producto: "Hot. Mayonesa 750g",
        imagen: "/placeholder.svg",
        
        categoria: "Lácteos y derivados",
        subcategoria: "Mayonesa",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Emulsiones",
        producto: "Hot. Salsa Rosada 830gr",
        imagen: "/placeholder.svg",
        
        categoria: "Lácteos y derivados",
        subcategoria: "Mayonesa",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Emulsiones",
        producto: "Salsa Rosada Galón 3650gr",
        imagen: "/placeholder.svg",
        
        categoria: "Lácteos y derivados",
        subcategoria: "Mayonesa",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Emulsiones",
        producto: "Mayonesa Galón 3350gr",
        imagen: "/placeholder.svg",
        
        categoria: "Lácteos y derivados",
        subcategoria: "Mayonesa",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Emulsiones",
        producto: "Mayonesa medio galón 1,6kg",
        imagen: "/placeholder.svg",
        
        categoria: "Lácteos y derivados",
        subcategoria: "Mayonesa",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Emulsiones",
        producto: "Mayonesa Kilo 850gr",
        imagen: "/placeholder.svg",
        
        categoria: "Lácteos y derivados",
        subcategoria: "Mayonesa",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Emulsiones",
        producto: "Mostaza Kilo 950gr",
        imagen: "/placeholder.svg",
        
        categoria: "Lácteos y derivados",
        subcategoria: "Mayonesa",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Cocción",
        producto: "Salsa Picantina 260gr",
        imagen: "/placeholder.svg",
        
        categoria: "Lácteos y derivados",
        subcategoria: "Mayonesa",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Cocción",
        producto: "Salsa B.B.Q. 290gr",
        imagen: "/placeholder.svg",
        
        categoria: "Lácteos y derivados",
        subcategoria: "Mayonesa",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Cocción",
        producto: "Homotético Salsa BBQ 930gr",
        imagen: "/placeholder.svg",
        
        categoria: "Grasas y aceites",
        subcategoria: "Condimentos",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Cocción",
        producto: "Salsa B.B.Q. Galón 4100gr",
        imagen: "/placeholder.svg",
        
        categoria: "Grasas y aceites",
        subcategoria: "Condimentos",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Cocción",
        producto: "Homotético Salsa base de Tomate 850gr",
        imagen: "/placeholder.svg",
        
        categoria: "Grasas y aceites",
        subcategoria: "Condimentos",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Cocción",
        producto: "Salsa a Base de Tomate 1000 g",
        imagen: "/placeholder.svg",
        
        categoria: "Grasas y aceites",
        subcategoria: "Condimentos",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Cocción",
        producto: "Salsa a Base de Tomate 1,85 kg",
        imagen: "/placeholder.svg",
        
        categoria: "Grasas y aceites",
        subcategoria: "Condimentos",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Cocción",
        producto: "Salsa a Base De Tomate Bolsa 1kg",
        imagen: "/placeholder.svg",
        
        categoria: "Grasas y aceites",
        subcategoria: "Condimentos",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Cocción",
        producto: "Salsa a Base De Tomate Bolsa 3,85kg",
        imagen: "/placeholder.svg",
        
        categoria: "Grasas y aceites",
        subcategoria: "Condimentos",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Salsas Líquidas",
        producto: "Salsa de Ajo 300cm3",
        imagen: "/placeholder.svg",
        
        categoria: "Grasas y aceites",
        subcategoria: "Condimentos",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Salsas Líquidas",
        producto: "Salsa de Ajo 150cm3",
        imagen: "/placeholder.svg",
        
        categoria: "Grasas y aceites",
        subcategoria: "Condimentos",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Salsas Líquidas",
        producto: "Salsa de Soya 300 cm3",
        imagen: "/placeholder.svg",
        
        categoria: "Grasas y aceites",
        subcategoria: "Condimentos",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Salsas Líquidas",
        producto: "Salsa de Soya 150cm3",
        imagen: "/placeholder.svg",
        
        categoria: "Grasas y aceites",
        subcategoria: "Condimentos",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Salsas Líquidas",
        producto: "Salsa Inglesa 300 cm3",
        imagen: "/placeholder.svg",
        
        categoria: "Grasas y aceites",
        subcategoria: "Condimentos",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Salsas Líquidas",
        producto: "Salsa Inglesa 150 cm3",
        imagen: "/placeholder.svg",
        
        categoria: "Grasas y aceites",
        subcategoria: "Condimentos",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Salsas Líquidas",
        producto: "Sazonador a base de especias semilíquido 160cm3",
        imagen: "/placeholder.svg",
        
        categoria: "Grasas y aceites",
        subcategoria: "Condimentos",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Salsas Líquidas",
        producto: "Salsa de Ajo Galón 3600cm3",
        imagen: "/placeholder.svg",
        
        categoria: "Grasas y aceites",
        subcategoria: "Condimentos",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Salsas Líquidas",
        producto: "Salsa Inglesa Galón 3600cm3",
        imagen: "/placeholder.svg",
        
        categoria: "Dulces y Snack",
        subcategoria: "Ketchup",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Salsas Líquidas",
        producto: "Salsa de Soja Galón 3600cm3",
        imagen: "/placeholder.svg",
        
        categoria: "Dulces y Snack",
        subcategoria: "Ketchup",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Licuados",
        producto: "Salsa de Ají Dulce 250gr",
        imagen: "/placeholder.svg",
        
        categoria: "Dulces y Snack",
        subcategoria: "Ketchup",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Licuados",
        producto: "Salsa de Ají Picante 250gr",
        imagen: "/placeholder.svg",
        
        categoria: "Dulces y Snack",
        subcategoria: "Ketchup",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Licuados",
        producto: "Homotético Salsa Ají Picante 740grs",
        imagen: "/placeholder.svg",
        
        categoria: "Dulces y Snack",
        subcategoria: "Ketchup",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Licuados",
        producto: "Salsa Picantico Criollo 310gr",
        imagen: "/placeholder.svg",
        
        categoria: "Dulces y Snack",
        subcategoria: "Ketchup",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Papas y Queso",
        producto: "YIL Papas ralladas 160gr",
        imagen: "/placeholder.svg",
        
        categoria: "Dulces y Snack",
        subcategoria: "Ketchup",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Papas y Queso",
        producto: "YIL Papas ralladas 1kg",
        imagen: "/placeholder.svg",
        
        categoria: "Dulces y Snack",
        subcategoria: "Ketchup",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Papas y Queso",
        producto: "Queso de año 180gr",
        imagen: "/placeholder.svg",
        
        categoria: "Dulces y Snack",
        subcategoria: "Ketchup",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Papas y Queso",
        producto: "Queso de año 1kg",
        imagen: "/placeholder.svg",
        
        categoria: "Dulces y Snack",
        subcategoria: "Ketchup",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Bases Saborizadas",
        producto: "Mezcla para Preparar Salsa sabor a Maíz 45gr",
        imagen: "/placeholder.svg",
        
        categoria: "Dulces y Snack",
        subcategoria: "Ketchup",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Bases Saborizadas",
        producto: "Mezcla para Preparar Salsa Tártara 45gr",
        imagen: "/placeholder.svg",
        
        categoria: "Dulces y Snack",
        subcategoria: "Ketchup",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Bases Saborizadas",
        producto: "Mezcla para Preparar Salsa sabor a Tocineta 45gr",
        imagen: "/placeholder.svg",
        
        categoria: "Dulces y Snack",
        subcategoria: "Ketchup",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Bases Saborizadas",
        producto: "Mezcla para Preparar Salsa sabor a Queso Cheddar 45gr",
        imagen: "/placeholder.svg",
        
        categoria: "Dulces y Snack",
        subcategoria: "Ketchup",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Bases Saborizadas",
        producto: "Mezcla para Preparar Salsa sabor a Ajo Perejil 45gr",
        imagen: "/placeholder.svg",
        
        categoria: "Dulces y Snack",
        subcategoria: "Ketchup",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Mermes",
        producto: "Merme De Guayaba 290gr",
        imagen: "/placeholder.svg",
        
        categoria: "Dulces y Snack",
        subcategoria: "Ketchup",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Mermes",
        producto: "Merme Guanábana Y Papelón 280 gr",
        imagen: "/placeholder.svg",
        
        categoria: "Salsas, aderezos y condimentos",
        subcategoria: "Mayonesa",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Mermes",
        producto: "Merme Durazno 270gr",
        imagen: "/placeholder.svg",
        
        categoria: "Salsas, aderezos y condimentos",
        subcategoria: "Mayonesa",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Mermes",
        producto: "Aderezo a Base de Piña 'Ananá' 280gr",
        imagen: "/placeholder.svg",
        
        categoria: "Salsas, aderezos y condimentos",
        subcategoria: "Mayonesa",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Operaciones",
        lineaoperacion: "Línea de Mermes",
        producto: "Sirope De Papelón Y Canela 310gr",
        imagen: "/placeholder.svg",
        
        categoria: "Salsas, aderezos y condimentos",
        subcategoria: "Mayonesa",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Consumo Masivo",
        producto: "Salsa Sabor a Maíz 240gr",
        imagen: "/placeholder.svg",
        
        categoria: "Salsas, aderezos y condimentos",
        subcategoria: "Mayonesa",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Consumo Masivo",
        producto: "Salsa Sabor A Queso Cheddar 240gr",
        imagen: "/placeholder.svg",
        
        categoria: "Salsas, aderezos y condimentos",
        subcategoria: "Mayonesa",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Consumo Masivo",
        producto: "Salsa Sabor A Tocineta 240gr",
        imagen: "/placeholder.svg",
        
        categoria: "Salsas, aderezos y condimentos",
        subcategoria: "Mayonesa",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Consumo Masivo",
        producto: "Salsa Tártara 240gr",
        imagen: "/placeholder.svg",
        
        categoria: "Salsas, aderezos y condimentos",
        subcategoria: "Mayonesa",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Consumo Masivo",
        producto: "Mayonesa 240gr",
        imagen: "/placeholder.svg",
        
        categoria: "Salsas, aderezos y condimentos",
        subcategoria: "Mayonesa",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Consumo Masivo",
        producto: "Aderezo de Mostaza y Miel 250gr",
        imagen: "/placeholder.svg",
        
        categoria: "Salsas, aderezos y condimentos",
        subcategoria: "Mayonesa",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Consumo Masivo",
        producto: "Mostaza Preparada 250gr",
        imagen: "/placeholder.svg",
        
        categoria: "Salsas, aderezos y condimentos",
        subcategoria: "Mayonesa",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Consumo Masivo",
        producto: "Salsa de Ají Dulce 250gr",
        imagen: "/placeholder.svg",
        
        categoria: "Salsas, aderezos y condimentos",
        subcategoria: "Mayonesa",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Consumo Masivo",
        producto: "Salsa de Ají Picante 250gr",
        imagen: "/placeholder.svg",
        
        categoria: "Salsas, aderezos y condimentos",
        subcategoria: "Mayonesa",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Consumo Masivo",
        producto: "Salsa Rosada 260gr",
        imagen: "/placeholder.svg",
        
        categoria: "Salsas, aderezos y condimentos",
        subcategoria: "Mayonesa",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Consumo Masivo",
        producto: "Salsa Picantina 260gr",
        imagen: "/placeholder.svg",
        
        categoria: "Salsas, aderezos y condimentos",
        subcategoria: "Mayonesa",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Consumo Masivo",
        producto: "Aderezo a Base de Piña 'Ananá' 280gr",
        imagen: "/placeholder.svg",
        
        categoria: "Salsas, aderezos y condimentos",
        subcategoria: "Mayonesa",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Consumo Masivo",
        producto: "Salsa B.B.Q. 290gr",
        imagen: "/placeholder.svg",
        
        categoria: "Salsas, aderezos y condimentos",
        subcategoria: "Mayonesa",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Consumo Masivo",
        producto: "Sirope De Papelón Y Canela 310gr",
        imagen: "/placeholder.svg",
        
        categoria: "Salsas, aderezos y condimentos",
        subcategoria: "Mayonesa",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Consumo Masivo",
        producto: "Merme De Guayaba 290gr",
        imagen: "/placeholder.svg",
        
        categoria: "Salsas, aderezos y condimentos",
        subcategoria: "Mayonesa",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Consumo Masivo",
        producto: "Merme Guanábana Y Papelón 280 gr",
        imagen: "/placeholder.svg",
        
        categoria: "Salsas, aderezos y condimentos",
        subcategoria: "Mayonesa",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Consumo Masivo",
        producto: "Merme Durazno 270gr",
        imagen: "/placeholder.svg",
        
        categoria: "Salsas, aderezos y condimentos",
        subcategoria: "Mayonesa",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Consumo Masivo",
        producto: "Homotético Salsa Sabor A Maíz 740gr",
        imagen: "/placeholder.svg",
        
        categoria: "Salsas, aderezos y condimentos",
        subcategoria: "Mayonesa",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Consumo Masivo",
        producto: "Homotético Salsa Sabor A Queso Cheddar 740gr",
        imagen: "/placeholder.svg",
        
        categoria: "Bebidas",
        subcategoria: "Sasonadores",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Consumo Masivo",
        producto: "Homotético Salsa Tártara 740gr",
        imagen: "/placeholder.svg",
        
        categoria: "Bebidas",
        subcategoria: "Sasonadores",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Consumo Masivo",
        producto: "Homotético Mayonesa 750g",
        imagen: "/placeholder.svg",
        
        categoria: "Bebidas",
        subcategoria: "Sasonadores",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Consumo Masivo",
        producto: "Homotético Salsa Ají Picante 740grs",
        imagen: "/placeholder.svg",
        
        categoria: "Bebidas",
        subcategoria: "Sasonadores",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Consumo Masivo",
        producto: "Homotético Salsa Rosada 830gr",
        imagen: "/placeholder.svg",
        
        categoria: "Bebidas",
        subcategoria: "Sasonadores",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Consumo Masivo",
        producto: "Mezcla para Salsa sabor a Maíz 45gr",
        imagen: "/placeholder.svg",
        
        categoria: "Bebidas",
        subcategoria: "Sasonadores",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Consumo Masivo",
        producto: "YIL Papas ralladas 160gr",
        imagen: "/placeholder.svg",
        
        categoria: "Bebidas",
        subcategoria: "Sasonadores",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Consumo Masivo",
        producto: "Queso de año 180gr",
        imagen: "/placeholder.svg",
        
        categoria: "Bebidas",
        subcategoria: "Sasonadores",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Food Service",
        producto: "Salsa A Base De Tomate Bolsa 3850gr",
        imagen: "/placeholder.svg",
        
        categoria: "Bebidas",
        subcategoria: "Sasonadores",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Food Service",
        producto: "Salsa A Base De Tomate Bolsa 1000gr",
        imagen: "/placeholder.svg",
        
        categoria: "Bebidas",
        subcategoria: "Sasonadores",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Food Service",
        producto: "Mostaza Kilo 950gr",
        imagen: "/placeholder.svg",
        
        categoria: "Bebidas",
        subcategoria: "Sasonadores",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Food Service",
        producto: "Mostaza Galón 3800gr",
        imagen: "/placeholder.svg",
        
        categoria: "Bebidas",
        subcategoria: "Sasonadores",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Food Service",
        producto: "Aderezo de Mostaza Bolsa 1000gr",
        imagen: "/placeholder.svg",
        
        categoria: "Bebidas",
        subcategoria: "Sasonadores",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Food Service",
        producto: "Aderezo de Mostaza Bolsa-Galón 4000gr",
        imagen: "/placeholder.svg",
        
        categoria: "Bebidas",
        subcategoria: "Sasonadores",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Food Service",
        producto: "Salsa B.B.Q. Galón 4100gr",
        imagen: "/placeholder.svg",
        
        categoria: "Bebidas",
        subcategoria: "Sasonadores",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Food Service",
        producto: "Salsa B.B.Q. 2kg",
        imagen: "/placeholder.svg",
        
        categoria: "Bebidas",
        subcategoria: "Sasonadores",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Food Service",
        producto: "Salsa Sabor A Queso Cheddar Galón 3200gr",
        imagen: "/placeholder.svg",
        
        categoria: "Bebidas",
        subcategoria: "Sasonadores",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Food Service",
        producto: "Salsa Rosada Galón 3650gr",
        imagen: "/placeholder.svg",
        
        categoria: "Bebidas",
        subcategoria: "Sasonadores",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Food Service",
        producto: "Mayonesa Galón 3350gr",
        imagen: "/placeholder.svg",
        
        categoria: "Bebidas",
        subcategoria: "Sasonadores",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Food Service",
        producto: "Mayonesa Kilo 850gr",
        imagen: "/placeholder.svg",
        
        categoria: "Bebidas",
        subcategoria: "Sasonadores",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Food Service",
        producto: "Preparado de Mayonesa Bolsa 1000gr",
        imagen: "/placeholder.svg",
        
        categoria: "Bebidas",
        subcategoria: "Sasonadores",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Food Service",
        producto: "Preparado de Mayonesa Bolsa 3,35kg",
        imagen: "/placeholder.svg",
        
        categoria: "Bebidas",
        subcategoria: "Sasonadores",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Food Service",
        producto: "Salsa de Ajo Galón 3600cm3",
        imagen: "/placeholder.svg",
        
        categoria: "Bebidas",
        subcategoria: "Sasonadores",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Food Service",
        producto: "Salsa Inglesa Galón 3600cm3",
        imagen: "/placeholder.svg",
        
        categoria: "Bebidas",
        subcategoria: "Sasonadores",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Food Service",
        producto: "Salsa de Soja Galón 3600cm3",
        imagen: "/placeholder.svg",
        
        categoria: "Bebidas",
        subcategoria: "Sasonadores",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Food Service",
        producto: "Homotético Salsa Sabor A Maíz 740gr",
        imagen: "/placeholder.svg",
        
        categoria: "Bebidas",
        subcategoria: "Sasonadores",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Food Service",
        producto: "Homotético Salsa Sabor A Queso Cheddar 740gr",
        imagen: "/placeholder.svg",
        
        categoria: "Bebidas",
        subcategoria: "Sasonadores",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Food Service",
        producto: "Homotético Salsa Tártara 740gr",
        imagen: "/placeholder.svg",
        
        categoria: "Bebidas",
        subcategoria: "Sasonadores",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Food Service",
        producto: "Homotético Mayonesa 750g",
        imagen: "/placeholder.svg",
        
        categoria: "Bebidas",
        subcategoria: "Sasonadores",
        marca: "Fritz",
        clasificacioncliente: "Food Service",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Food Service",
        producto: "Homotético Salsa Ají Picante 740grs",
        imagen: "/placeholder.svg",
        
        categoria: "Salsas, aderezos y condimentos",
        subcategoria: "Mostaza",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Food Service",
        producto: "Homotético Salsa Rosada 830gr",
        imagen: "/placeholder.svg",
        
        categoria: "Salsas, aderezos y condimentos",
        subcategoria: "Mostaza",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Food Service",
        producto: "Mezcla para Preparar Salsa sabor a Maíz 45gr",
        imagen: "/placeholder.svg",
        
        categoria: "Salsas, aderezos y condimentos",
        subcategoria: "Mostaza",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Food Service",
        producto: "Mezcla para Preparar Salsa Tártara 45gr",
        imagen: "/placeholder.svg",
        
        categoria: "Salsas, aderezos y condimentos",
        subcategoria: "Mostaza",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Food Service",
        producto: "Mezcla para Preparar Salsa sabor a Tocineta 45gr",
        imagen: "/placeholder.svg",
        
        categoria: "Salsas, aderezos y condimentos",
        subcategoria: "Mostaza",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Food Service",
        producto: "Mezcla para Preparar Salsa sabor a Queso Cheddar 45gr",
        imagen: "/placeholder.svg",
        
        categoria: "Salsas, aderezos y condimentos",
        subcategoria: "Mostaza",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Food Service",
        producto: "YIL Papas ralladas 160gr",
        imagen: "/placeholder.svg",
        
        categoria: "Salsas, aderezos y condimentos",
        subcategoria: "Mostaza",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Food Service",
        producto: "YIL Papas ralladas 1kg",
        imagen: "/placeholder.svg",
        
        categoria: "Salsas, aderezos y condimentos",
        subcategoria: "Mostaza",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Food Service",
        producto: "Queso de año 180gr",
        imagen: "/placeholder.svg",
        
        categoria: "Salsas, aderezos y condimentos",
        subcategoria: "Mostaza",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },
    {
        tipo: "Clientes/Venta",
        lineaoperacion: "Food Service",
        producto: "Queso de año 1kg",
        imagen: "/placeholder.svg",
        
        categoria: "Salsas, aderezos y condimentos",
        subcategoria: "Mostaza",
        marca: "Fritz",
        clasificacioncliente: "Consumo Masivo",
    },


];

//console.log(JSON.stringify(dataClasificacion, null, 2));
